export const SEED_CURRENCIES = [
  { code: 'USD', name: 'DÓLARES EE.UU.',    symbol: '$',    isoCode: '840', buyRate: 1,          sellRate: 1,          isActive: true, isDefault: true  },
  { code: 'EUR', name: 'EUROS',              symbol: '€',    isoCode: '978', buyRate: 1,          sellRate: 1,          isActive: true, isDefault: false },
  { code: 'ARS', name: 'PESOS (ARG)',        symbol: 'AR$',  isoCode: '32',  buyRate: 16.684,     sellRate: 16.684,     isActive: true, isDefault: false },
  { code: 'BOB', name: 'BOLIVIANOS',         symbol: 'Bs.',  isoCode: '68',  buyRate: 6.91,       sellRate: 6.91,       isActive: true, isDefault: false },
  { code: 'BRL', name: 'REALES',             symbol: 'R$',   isoCode: '986', buyRate: 5.0,        sellRate: 5.0,        isActive: true, isDefault: false },
  { code: 'CLP', name: 'PESOS (CHL)',        symbol: 'CLP$', isoCode: '152', buyRate: 704.02,     sellRate: 704.02,     isActive: true, isDefault: false },
  { code: 'COP', name: 'PESOS (COL)',        symbol: 'CO$',  isoCode: '170', buyRate: 3140.68,    sellRate: 3140.68,    isActive: true, isDefault: false },
  { code: 'CRC', name: 'COLONES',            symbol: '₡',    isoCode: '188', buyRate: 536.02,     sellRate: 536.02,     isActive: true, isDefault: false },
  { code: 'CUP', name: 'PESOS (CUB)',        symbol: '$MN',  isoCode: '192', buyRate: 24.0,       sellRate: 24.0,       isActive: true, isDefault: false },
  { code: 'DOP', name: 'PESOS DOMINICANOS',  symbol: 'RD$',  isoCode: '214', buyRate: 49.76,      sellRate: 49.76,      isActive: true, isDefault: false },
  { code: 'GTQ', name: 'QUETZALES',          symbol: 'Q',    isoCode: '320', buyRate: 7.72,       sellRate: 7.72,       isActive: true, isDefault: false },
  { code: 'HNL', name: 'LEMPIRAS',           symbol: 'L',    isoCode: '340', buyRate: 24.62,      sellRate: 24.62,      isActive: true, isDefault: false },
  { code: 'HTG', name: 'GOURDES',            symbol: 'G',    isoCode: '332', buyRate: 132.0,      sellRate: 132.0,      isActive: true, isDefault: false },
  { code: 'MXN', name: 'PESOS (MEX)',        symbol: 'MX$',  isoCode: '484', buyRate: 23.37,      sellRate: 23.37,      isActive: true, isDefault: false },
  { code: 'NIO', name: 'CÓRDOBAS',           symbol: 'C$',   isoCode: '558', buyRate: 36.56,      sellRate: 36.56,      isActive: true, isDefault: false },
  { code: 'PAB', name: 'BALBOAS',            symbol: 'B/.',  isoCode: '590', buyRate: 1.0,        sellRate: 1.0,        isActive: true, isDefault: false },
  { code: 'PEN', name: 'SOLES',              symbol: 'S/.',  isoCode: '604', buyRate: 3.74,       sellRate: 3.74,       isActive: true, isDefault: false },
  { code: 'PYG', name: 'GUARANÍES',          symbol: '₲',    isoCode: '600', buyRate: 7390.0,     sellRate: 7390.0,     isActive: true, isDefault: false },
  { code: 'SVC', name: 'COLONES (SLV)',      symbol: '₡',    isoCode: '222', buyRate: 8.75,       sellRate: 8.75,       isActive: true, isDefault: false },
  { code: 'TTD', name: 'DÓLARES TRINIDAD',   symbol: 'TT$',  isoCode: '780', buyRate: 6.77,       sellRate: 6.77,       isActive: true, isDefault: false },
  { code: 'UYU', name: 'PESOS (URY)',        symbol: '$U',   isoCode: '858', buyRate: 39.06,      sellRate: 39.06,      isActive: true, isDefault: false },
  { code: 'VES', name: 'BOLÍVARES SOBERANOS',symbol: 'Bs.S', isoCode: '928', buyRate: 36.0,       sellRate: 36.0,       isActive: true, isDefault: false },
  { code: 'GBP', name: 'LIBRAS ESTERLINAS',  symbol: '£',    isoCode: '826', buyRate: 0.865,      sellRate: 0.865,      isActive: true, isDefault: false },
];

// Países de Latinoamérica + España + EE.UU. como referencia
// Formato: [ISO-3, ISO-2, Nombre]
export const SEED_COUNTRIES: [string, string, string][] = [
  ['ARG', 'AR', 'Argentina'],
  ['BLZ', 'BZ', 'Belice'],
  ['BOL', 'BO', 'Bolivia'],
  ['BRA', 'BR', 'Brasil'],
  ['CHL', 'CL', 'Chile'],
  ['COL', 'CO', 'Colombia'],
  ['CRI', 'CR', 'Costa Rica'],
  ['CUB', 'CU', 'Cuba'],
  ['DOM', 'DO', 'República Dominicana'],
  ['ECU', 'EC', 'Ecuador'],
  ['SLV', 'SV', 'El Salvador'],
  ['ESP', 'ES', 'España'],
  ['GTM', 'GT', 'Guatemala'],
  ['GUY', 'GY', 'Guyana'],
  ['HTI', 'HT', 'Haití'],
  ['HND', 'HN', 'Honduras'],
  ['JAM', 'JM', 'Jamaica'],
  ['MEX', 'MX', 'México'],
  ['NIC', 'NI', 'Nicaragua'],
  ['PAN', 'PA', 'Panamá'],
  ['PRY', 'PY', 'Paraguay'],
  ['PER', 'PE', 'Perú'],
  ['PRI', 'PR', 'Puerto Rico'],
  ['SUR', 'SR', 'Surinam'],
  ['TTO', 'TT', 'Trinidad y Tobago'],
  ['URY', 'UY', 'Uruguay'],
  ['USA', 'US', 'Estados Unidos'],
  ['VEN', 'VE', 'Venezuela'],
];
