import { Timestamp } from '@angular/fire/firestore';

// ─── Journal Entry Status ─────────────────────────────────────────────────────

export type JournalEntryStatus = 'draft' | 'posted' | 'cancelled';

export const JOURNAL_ENTRY_STATUS_LABELS: Record<JournalEntryStatus, string> = {
  draft:     'Borrador',
  posted:    'Contabilizado',
  cancelled: 'Anulado'
};

export const JOURNAL_ENTRY_STATUS_COLORS: Record<JournalEntryStatus, string> = {
  draft:     'secondary',
  posted:    'success',
  cancelled: 'danger'
};

// ─── Journal Entry Type ───────────────────────────────────────────────────────

export type JournalEntryType =
  | 'manual'
  | 'automatic'    // generated by invoice or retention
  | 'opening'      // asiento de apertura
  | 'closing'      // asiento de cierre
  | 'adjustment';  // ajuste contable

export const JOURNAL_ENTRY_TYPE_LABELS: Record<JournalEntryType, string> = {
  manual:    'Manual',
  automatic: 'Automático',
  opening:   'Apertura',
  closing:   'Cierre',
  adjustment:'Ajuste'
};

export const JOURNAL_ENTRY_TYPE_COLORS: Record<JournalEntryType, string> = {
  manual:    'primary',
  automatic: 'info',
  opening:   'warning',
  closing:   'secondary',
  adjustment:'dark'
};

// ─── Journal Entry Line ───────────────────────────────────────────────────────

export interface JournalEntryLine {
  id: string;
  accountCode: string;
  accountName: string;
  debit: number;
  credit: number;
  costCenterId?: string | null;
  costCenterName?: string | null;
  description?: string;
}

// ─── Journal Entry document ───────────────────────────────────────────────────
// Stored at: /companies/{companyId}/journal_entries/{entryId}

export interface JournalEntry {
  id: string;
  number: number;            // sequential per period
  date: Timestamp;
  description: string;
  periodId: string;          // reference to accounting_periods/{periodId}
  periodYear: number;        // denormalized for easy filtering
  type: JournalEntryType;
  status: JournalEntryStatus;
  reference?: string;        // invoice number, retention number, etc.
  referenceId?: string;      // document ID in Firestore
  lines: JournalEntryLine[];
  totalDebit: number;
  totalCredit: number;
  isBalanced: boolean;       // totalDebit === totalCredit
  createdBy: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  updatedBy?: string;
  cancelledAt?: Timestamp;
  cancelledBy?: string;
  cancelReason?: string;
}

// ─── Libro Mayor line (UI computed) ──────────────────────────────────────────

export interface LibroMayorLine {
  entryId: string;
  entryNumber: number;
  date: Timestamp;
  description: string;
  reference: string;
  debit: number;
  credit: number;
  balance: number;       // running balance
  type: JournalEntryType;
}

// ─── Balance de Comprobacion ──────────────────────────────────────────────────

export interface BalanceComprobacionLine {
  accountCode: string;
  accountName: string;
  accountType: string;
  sumDebit: number;
  sumCredit: number;
  initialDebit: number;
  initialCredit: number;
  finalDebit: number;
  finalCredit: number;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function calcEntryTotals(lines: JournalEntryLine[]): { totalDebit: number; totalCredit: number; isBalanced: boolean } {
  const totalDebit  = round2(lines.reduce((s, l) => s + (l.debit  ?? 0), 0));
  const totalCredit = round2(lines.reduce((s, l) => s + (l.credit ?? 0), 0));
  return { totalDebit, totalCredit, isBalanced: totalDebit === totalCredit };
}

function round2(n: number): number { return Math.round(n * 100) / 100; }
