declare interface Recharges {
    rechargeId?: string,
    rechargeAmountCop?: string,
    rechargeAmountUsd?: string,
    rechargeAmountVef?: string,
    rechargeCreatedAt?: string,
    rechargeCreatedBy?: string,
    rechargeObservations?: string,
    rechargePaymentMethodBank?: string,
    rechargePaymentMethodId?: string,
    rechargePaymentMethodName?: string,
    rechargeStatus?: string,
    rechargeTransactionReference?: string,
    rechargeUpdateAt?: string,
    rechargeUserUid?: string,
    rechargeUserName?: string,
    rechargeUserPhone?: string,
    rechargeVerifiedBy?: string,
    rechargeVoucherUrl?: string,
} 